2025-09-14 16:41:39,904 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:41:39,905 - __main__ - ERROR - Error in main execution: name 'NewsProcessor' is not defined
2025-09-14 16:43:51,282 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:43:51,282 - __main__ - ERROR - Error in main execution: 'module' object is not callable
2025-09-14 16:49:36,831 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:49:36,831 - __main__ - ERROR - Error in main execution: 'module' object is not callable
2025-09-14 16:51:05,347 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:51:05,347 - __main__ - ERROR - Error in main execution: 'topics'
2025-09-14 16:51:53,334 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:51:53,339 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 16:51:53,347 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 16:51:53,347 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 16:51:53,348 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 16:53:23,133 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:53:23,136 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 16:53:23,142 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 16:53:23,143 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 16:53:23,143 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 16:53:23,144 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 16:53:23,144 - __main__ - INFO - Processor closed
2025-09-14 16:54:08,195 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:54:08,198 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 16:54:08,204 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 16:54:08,204 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 16:54:08,205 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 16:54:08,205 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 16:54:08,205 - __main__ - INFO - Processor closed
2025-09-14 16:54:30,389 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:54:30,392 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 16:54:30,399 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 16:54:30,402 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 16:54:30,404 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 16:54:30,405 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 16:54:30,406 - __main__ - INFO - Processor closed
2025-09-14 16:57:18,862 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:57:18,865 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 16:57:18,869 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 16:57:18,870 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 16:57:18,870 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 16:57:18,870 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 16:57:18,870 - __main__ - INFO - Processor closed
2025-09-14 16:58:30,230 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:58:30,233 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 16:58:30,258 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 16:58:30,258 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 16:58:30,259 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 16:58:30,260 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 16:58:30,260 - __main__ - INFO - Processor closed
2025-09-14 16:59:58,641 - __main__ - INFO - Configuration loaded successfully
2025-09-14 16:59:58,641 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 16:59:58,641 - __main__ - INFO - Processor closed
2025-09-14 17:00:26,805 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:00:26,807 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:00:26,815 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:00:26,815 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:00:26,815 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 17:00:26,816 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:00:26,816 - __main__ - INFO - Processor closed
2025-09-14 17:03:05,490 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:03:05,493 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:03:05,605 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:03:05,605 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:03:05,606 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 17:03:05,607 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:03:05,607 - __main__ - INFO - Processor closed
2025-09-14 17:04:12,118 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:04:12,120 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:04:12,125 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:04:12,125 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:04:12,126 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 17:04:12,126 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:04:12,126 - __main__ - INFO - Processor closed
2025-09-14 17:09:18,533 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:09:18,536 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:09:18,541 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:09:18,542 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:09:18,542 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 17:09:18,543 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:09:18,543 - __main__ - INFO - Processor closed
2025-09-14 17:09:41,702 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:09:41,705 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:09:41,712 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:09:41,712 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:09:41,712 - conntector.NewsProcessor - INFO - Starting to consume messages
2025-09-14 17:09:41,713 - conntector.NewsProcessor - INFO - condumer info <kafka.consumer.group.KafkaConsumer object at 0x71704dcc6b40>
2025-09-14 17:09:41,717 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:09:41,717 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:09:41,717 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:09:41,718 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:09:41,820 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:09:41,821 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:09:41,821 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:09:41,821 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:09:41,923 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:09:41,925 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:09:41,926 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:09:41,927 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:09:42,156 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:09:42,157 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:09:42,157 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:09:42,157 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:09:42,620 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:09:42,620 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:09:42,620 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:09:42,620 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:09:43,554 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:09:43,554 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:09:43,554 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:09:43,554 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:09:45,008 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:09:45,008 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:09:45,008 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:09:45,009 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:09:48,405 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:09:48,405 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:09:48,405 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:09:48,405 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:09:55,974 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:09:55,974 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:09:55,974 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:09:55,974 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:09:59,932 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:09:59,932 - __main__ - INFO - Processor closed
2025-09-14 17:10:53,876 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:10:53,879 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:10:53,884 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:10:53,884 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:10:53,885 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 17:10:53,885 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:10:53,885 - __main__ - INFO - Processor closed
2025-09-14 17:11:17,350 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:11:17,354 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:11:17,362 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:11:17,363 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:11:17,364 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 17:11:17,365 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:11:17,365 - __main__ - INFO - Processor closed
2025-09-14 17:12:57,849 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': ['raw-news', 'processed-news'], 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:12:57,849 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:12:57,851 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:12:57,858 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:12:57,858 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:12:57,859 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 17:12:57,859 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:12:57,859 - __main__ - INFO - Processor closed
2025-09-14 17:14:21,745 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': ['raw-news', 'processed-news'], 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:14:21,745 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:14:21,750 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:14:21,756 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:14:21,756 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:14:21,757 - __main__ - ERROR - Error in main execution: All topics must be strings
2025-09-14 17:14:21,757 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:14:21,757 - __main__ - INFO - Processor closed
2025-09-14 17:16:50,045 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': ['raw-news', 'processed-news'], 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:16:50,045 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:16:50,049 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:16:50,055 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:16:50,056 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:16:50,057 - __main__ - ERROR - Error in main execution: Topic name "['raw-news', 'processed-news']" is illegal, it contains a character other than ASCII alphanumerics, ".", "_" and "-"
2025-09-14 17:16:50,057 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:16:50,057 - __main__ - INFO - Processor closed
2025-09-14 17:17:23,956 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': 'raw-news,processed-news', 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:17:23,957 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:17:23,960 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:17:23,968 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:17:23,969 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:17:23,970 - __main__ - ERROR - Error in main execution: Topic name "raw-news,processed-news" is illegal, it contains a character other than ASCII alphanumerics, ".", "_" and "-"
2025-09-14 17:17:23,970 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:17:23,970 - __main__ - INFO - Processor closed
2025-09-14 17:20:50,141 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': ['raw-news', 'processed-news'], 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:20:50,141 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:20:50,144 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:20:50,150 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:20:50,150 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:20:50,151 - __main__ - ERROR - Error in main execution: unhashable type: 'list'
2025-09-14 17:20:50,151 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:20:50,151 - __main__ - INFO - Processor closed
2025-09-14 17:21:06,928 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': ['raw-news', 'processed-news'], 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:21:06,929 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:21:06,931 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:21:06,936 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:21:06,936 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:21:06,937 - __main__ - ERROR - Error in main execution: All topics must be strings
2025-09-14 17:21:06,937 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:21:06,937 - __main__ - INFO - Processor closed
2025-09-14 17:21:54,850 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': ['raw-news', 'processed-news'], 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:21:54,850 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:21:54,850 - conntector.NewsProcessor - INFO - Kafka topics: ('raw-news', 'processed-news')
2025-09-14 17:21:54,853 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:21:54,859 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:21:54,860 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:21:54,860 - __main__ - ERROR - Error in main execution: All topics must be strings
2025-09-14 17:21:54,861 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:21:54,861 - __main__ - INFO - Processor closed
2025-09-14 17:22:59,221 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': ['raw-news', 'processed-news'], 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:22:59,221 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:22:59,221 - conntector.NewsProcessor - INFO - Kafka topics: ('raw-news', 'processed-news')
2025-09-14 17:22:59,225 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:22:59,231 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:22:59,231 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:22:59,232 - __main__ - ERROR - Error in main execution: All topics must be strings
2025-09-14 17:22:59,233 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:22:59,233 - __main__ - INFO - Processor closed
2025-09-14 17:23:27,787 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': ['raw-news', 'processed-news'], 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:23:27,788 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:23:27,788 - conntector.NewsProcessor - INFO - Kafka topics: <class 'tuple'>
2025-09-14 17:23:27,792 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:23:27,799 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:23:27,799 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:23:27,800 - __main__ - ERROR - Error in main execution: All topics must be strings
2025-09-14 17:23:27,800 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:23:27,800 - __main__ - INFO - Processor closed
2025-09-14 17:23:49,615 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': ['raw-news', 'processed-news'], 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:23:49,615 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:23:49,615 - conntector.NewsProcessor - INFO - Kafka topics: <class 'str'>
2025-09-14 17:23:49,620 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:23:49,629 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:23:49,629 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:23:49,630 - __main__ - ERROR - Error in main execution: All topics must be strings
2025-09-14 17:23:49,630 - conntector.NewsProcessor - INFO - Closing NewsProcessor
2025-09-14 17:23:49,631 - __main__ - INFO - Processor closed
2025-09-14 17:24:05,210 - __main__ - INFO - Configuration loaded successfully: {'storage': {'hdfs': {'host': 'localhost', 'port': 9000, 'user': 'hadoop', 'base_path': '/data/news', 'formats': [{'cold': 'parquet'}, {'archive': 'avro'}], 'compresison': 'snappy', 'replication': 3}, 'hbase': {'host': 'localhost', 'port': 9090, 'table': 'news', 'column_family': 'cf', 'max-versions': 3, 'block_cache': True, 'bloom_filter': True}, 'retention': {'hot_data_days': 7, 'warm_data_days': 30, 'cold_data_days': 365}, 'processing': {'batch_size': 1000, 'max_workers': 4, 'timeout': 30}}, 'logging': {'level': 'INFO'}, 'kafka': {'bootstrap_servers': '192.168.100.2:9092', 'topics': ['raw-news', 'processed-news'], 'group_id': 'news_storage_consumer'}, 'monitoring': {'prometheus_port': 8000, 'log_level': 'INFO'}}
2025-09-14 17:24:05,210 - __main__ - INFO - Configuration loaded successfully
2025-09-14 17:24:05,210 - conntector.NewsProcessor - INFO - Kafka topics: <class 'str'>
2025-09-14 17:24:05,213 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connecting> [IPv4 ('192.168.100.2', 9092)]>: connecting to 192.168.100.2:9092 [('192.168.100.2', 9092) IPv4]
2025-09-14 17:24:05,218 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <checking_api_versions_recv> [IPv4 ('192.168.100.2', 9092)]>: Broker version identified as 2.6
2025-09-14 17:24:05,219 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=192.168.100.2:9092 <connected> [IPv4 ('192.168.100.2', 9092)]>: Connection complete.
2025-09-14 17:24:05,220 - kafka.consumer.subscription_state - INFO - Updating subscribed topics to: ('raw-news',)
2025-09-14 17:24:05,220 - conntector.NewsProcessor - INFO - Starting to consume messages
2025-09-14 17:24:05,220 - conntector.NewsProcessor - INFO - condumer info <kafka.consumer.group.KafkaConsumer object at 0x79785465eab0>
2025-09-14 17:24:05,863 - kafka.cluster - ERROR - Topic raw-news not found in cluster metadata
2025-09-14 17:24:05,864 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:05,864 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:05,864 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:05,864 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:24:05,965 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:05,966 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:05,966 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:05,966 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:24:06,067 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:06,068 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:06,068 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:06,068 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:24:06,290 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:06,291 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:06,291 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:06,292 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:24:06,639 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:06,639 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:06,640 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:06,640 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:24:07,290 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:07,290 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:07,290 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:07,290 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:24:08,903 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:08,904 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:08,904 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:08,904 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:24:11,958 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:11,958 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:11,958 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:11,958 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:24:17,586 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:17,586 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:17,586 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:17,587 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:24:31,507 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:31,507 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:31,507 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:31,507 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:24:56,992 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:24:56,992 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:24:56,992 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:24:56,993 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:25:26,189 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:25:26,189 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:25:26,189 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:25:26,189 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-09-14 17:25:59,543 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
2025-09-14 17:25:59,545 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
2025-09-14 17:25:59,545 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-09-14 17:25:59,546 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
